library(readr)
all_info_ipt <- read_csv("all_info_ipt.csv")
library(lme4)
m0 <- lmer (formula = ipt ~ 1 + (1|instance) + (1|pid), data = all_info_ipt)
m1 <- lmer (formula = ipt ~ 1 + order + (1|instance) + (1|pid), data = all_info_ipt)
m2 <- lmer (formula = ipt ~ 1 + condition + (1|instance) + (1|pid), data = all_info_ipt)
m3 <- lmer (formula = ipt ~ 1 + order + condition + (1|instance) + (1|pid), data = all_info_ipt)
anova(m0,m1,m2,m3)
library(ggplot2)
library("magrittr")
library("dplyr")
mean_order_time <- all_info_ipt %>% group_by(order) %>% summarise_at(vars(ipt),list(mean = median, sd=sd)) %>% as.data.frame()
p<-ggplot(mean_order_time, aes(x = order,  y =mean)) + geom_line()  + geom_point()
p+ylab("median of initial planning time")
full_info_ipt <- all_info_ipt[all_info_ipt$condition == 1, ]
default_info_ipt<- all_info_ipt[all_info_ipt$condition == 0, ]
d0<-lmer(formula = ipt ~ 1 + order + (1|instance) + (1|pid), data = default_info_ipt)
d_rw <- lmer(formula = ipt ~ 1 + order + random + (1|pid), data = default_info_ipt)
d_hc <- lmer(formula = ipt ~ 1 + order + cm + (1|pid), data = default_info_ipt)
d_model<-lmer(formula = ipt ~ 1 + order + model + (1|pid), data = default_info_ipt)
d_bfs<-lmer(formula = ipt ~ 1 + order + bfs + (1|pid), data = default_info_ipt)
d_astar<-lmer(formula = ipt ~ 1 + order + astar_gc + (1|pid), data = default_info_ipt)
d_greedy<-lmer(formula = ipt ~ 1 + order + greedy_gc + (1|pid), data = default_info_ipt)
d_tree<-lmer(formula = ipt ~ 1 + order + tree_gc + (1|pid), data = default_info_ipt)
d_sh<-lmer(formula = ipt ~ 1 + order + start_hierarchy + (1|pid), data = default_info_ipt)
d_oc<-lmer(formula = ipt ~ 1 + order + optimal_cost + (1|pid), data = default_info_ipt)
d_1<-lmer(formula = ipt ~ 1 + order + lh1 + (1|pid), data = default_info_ipt)
d_2<-lmer(formula = ipt ~ 1 + order + lh2 + (1|pid), data = default_info_ipt)
d_3<-lmer(formula = ipt ~ 1 + order + lh3 + (1|pid), data = default_info_ipt)
d_4<-lmer(formula = ipt ~ 1 + order + lh4 + (1|pid), data = default_info_ipt)
d_5<-lmer(formula = ipt ~ 1 + order + lh5 + (1|pid), data = default_info_ipt)
d_6<-lmer(formula = ipt ~ 1 + order + lh6 + (1|pid), data = default_info_ipt)
d_7<-lmer(formula = ipt ~ 1 + order + lh7 + (1|pid), data = default_info_ipt)
anova(d0,d_rw,d_hc,d_model,d_bfs,d_astar,d_greedy,d_tree,d_oc,d_sh,d_1,d_2,d_3,d_4,d_5,d_6,d_7)
d_hc <- lmer(formula = ipt ~ 1 + order + cm + (1|pid), data = default_info_ipt)
default_info_ipt<- all_info_ipt[all_info_ipt$condition == 1, ]
d0<-lmer(formula = ipt ~ 1 + order + (1|instance) + (1|pid), data = default_info_ipt)
d_rw <- lmer(formula = ipt ~ 1 + order + random + (1|pid), data = default_info_ipt)
d_hc <- lmer(formula = ipt ~ 1 + order + cm + (1|pid), data = default_info_ipt)
d_model<-lmer(formula = ipt ~ 1 + order + model + (1|pid), data = default_info_ipt)
d_bfs<-lmer(formula = ipt ~ 1 + order + bfs + (1|pid), data = default_info_ipt)
d_astar<-lmer(formula = ipt ~ 1 + order + astar_gc + (1|pid), data = default_info_ipt)
d_greedy<-lmer(formula = ipt ~ 1 + order + greedy_gc + (1|pid), data = default_info_ipt)
d_tree<-lmer(formula = ipt ~ 1 + order + tree_gc + (1|pid), data = default_info_ipt)
d_sh<-lmer(formula = ipt ~ 1 + order + start_hierarchy + (1|pid), data = default_info_ipt)
d_oc<-lmer(formula = ipt ~ 1 + order + optimal_cost + (1|pid), data = default_info_ipt)
d_1<-lmer(formula = ipt ~ 1 + order + lh1 + (1|pid), data = default_info_ipt)
d_2<-lmer(formula = ipt ~ 1 + order + lh2 + (1|pid), data = default_info_ipt)
d_3<-lmer(formula = ipt ~ 1 + order + lh3 + (1|pid), data = default_info_ipt)
d_4<-lmer(formula = ipt ~ 1 + order + lh4 + (1|pid), data = default_info_ipt)
d_5<-lmer(formula = ipt ~ 1 + order + lh5 + (1|pid), data = default_info_ipt)
d_6<-lmer(formula = ipt ~ 1 + order + lh6 + (1|pid), data = default_info_ipt)
d_7<-lmer(formula = ipt ~ 1 + order + lh7 + (1|pid), data = default_info_ipt)
anova(d0,d_rw,d_hc,d_model,d_bfs,d_astar,d_greedy,d_tree,d_oc,d_sh,d_1,d_2,d_3,d_4,d_5,d_6,d_7)
